FROM node:18-alpine as base

RUN apk add --no-cache libc6-compat tini
WORKDIR /app
COPY package.json pnpm-lock.yaml ./

FROM base AS deps
RUN npm install -g pnpm
RUN pnpm install --prod --frozen-lockfile

FROM deps AS build
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm build

FROM base as prod
ENV NODE_ENV production
COPY --from=deps /app/node_modules /app/node_modules
COPY --from=build /app/dist /app/dist
EXPOSE 8080
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["sh", "-c", "pnpm start:prod"]
